import Head from 'next/head'
import Image from 'next/image'
import Footer from '@components/footer'
import Link from 'next/link';

function Button() {
  return (
    <div className="appear appear-third mx-auto flex">
      <div className="w-full rounded bg-gradient-to-r from-primary to-secondary p-0.5">
        <div className="relative flex h-full w-full items-center justify-center">
          <div className='absolute -inset-0.5 bg-gradient-to-r from-primary to-secondary blur-lg opacity-20'></div>
          <Link href='/search' passHref legacyBehavior>
            <button className='relative bg-black hover:bg-primary transition duration-500 ease-in-out '>Search</button>
          </Link>
        </div>
      </div>
    </div>
  )
}

export default function Home() {
  return (
    <>
      <Head>
        <title>YDOOC - Software as you need</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col h-screen justify-between'>
        <div className="appear appear-first flex items-center justify-center py-12 md:py-12">
          <Image
            alt={'YDOOC'}
            src={'/logo.svg'}
            loading="lazy"
            quality="100"
            width={250}
            height={178}
          />
        </div>
        <div className="flex flex-col items-center justify-center">
          <h1 className='appear appear-second text-4xl md:text-8xl font-bold text-center tracking-tighter'>Explore Marvel API
          </h1>
          <h2 className='appear appear-third text-xl md:text-2xl py-8 text-center'>A simple application to consume Marvel API from Marvel Developer Portal</h2>
          <Button></Button>
        </div>
        <Footer />
      </main>
    </>
  )
}
